name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Test openmodelica-library-testing
        id: test-action
        uses: ./
        with:
          package-name: MyLibrary
          package-version: 1.0.0
          modelica-file: examples/MyLibrary/package.mo
          dependencies: |
            Modelica 4.0.0+maint.om
          omc-version: stable
          reference-files-dir: examples/ReferenceFiles
          reference-files-format: csv
          reference-files-delimiter: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify action results
        shell: bash
        run: |
          echo "simulation-tests-passing: ${{ steps.test-action.outputs.simulation-tests-passing }}"
          echo "verification-tests-passing: ${{ steps.test-action.outputs.verification-tests-passing }}"

          if [ "${{ steps.test-action.outputs.simulation-tests-passing }}" == "True" ] && [ ${{ steps.test-action.outputs.n-simulation-passing }} == 2 ] && [ "${{ steps.test-action.outputs.verification-tests-passing }}" == "False" ] && [ ${{ steps.test-action.outputs.n-simulation-passing }} == 1 ]; then
            exit 0;
          else
            exit 1;
          fi
