name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Test openmodelica-library-testing
        id: test-action
        uses: ./
        with:
          package-name: MyLibrary
          package-version: 1.0.0
          modelica-file: examples/MyLibrary/package.mo
          dependencies: |
            Modelica 4.0.0+maint.om
          omc-version: stable
          reference-files-dir: examples/ReferenceFiles
          reference-files-format: csv
          reference-files-delimiter: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
